void	setpal(byte *);
void	stopfb(void);
void	flipfb(void);
void	initfb(void);
void	conscmd(void);
void	Sys_SendKeyEvents(void);
void	stepcd(void);
void	stepsnd(const view_t *);
void	stopcd(void);
void	pausecd(void);
void	resumecd(void);
void	playcd(int, bool);
void	cdcmd(cmd_t *);
void	shutcd(void);
void	stopallsfx(cmd_t *);
void	stopsfx(int, int);
void	startsfx(int, int, Sfx *, vec3_t, float, float);
void	localsfx(char *);
void	staticsfx(Sfx *, vec3_t, float, float);
void	sfxbegin(void);
void	sfxend(void);
void	touchsfx(char *);
Sfx*	precachesfx(char *);
void	shutsnd(void);
int	initcd(void);
int	initsnd(void);
void	setcvar(char*, char*);
void	setcvarv(char*, float);
void	abortdemo(void);
void	stopdemo(cmd_t *);
int	readcl(void);
void	timedemo(cmd_t *);
void	recdemo(cmd_t *);
void	playdemo(cmd_t *);
void	crc(u8int);
void	initcrc(void);
char*	ext(char*, char*);
void	radix(char*, char*);
void*	loadhunklmp(char *, int *);
void*	loadcachelmp(char *, mem_user_t *);
void*	loadstklmp(char *, void *, int, int *);
void	loadpoints(cmd_t *);
FILE*	openlmp(char *f, int *len);
FILE*	createfile(char *path);
void	removefile(char *path);
void	dumpcfg(void);
void	savnames(void);
int	dumpsav(char*, char*);
int	loadsav(char*);
void	closedm(void);
void	writedm(void);
int	readdm(void);
int	loaddm(char*);
int	opendm(char*, int);
void	initfs(char **paths);
#pragma varargck	argpos	fatal	1
_Noreturn void	fatal(char*, ...);
void*	emalloc(long);
s64int	flen(int);
double	dtime(void);
void	game_shutdown(void);
u64int	nanosec(void);

char *lerr(void);
int	sys_mkdir(char *path);
char *sys_timestamp(void);
char *sys_wrpath(void);

long sndqueued(void);
void sndstop(void);
void sndwrite(byte *buf, long sz);
void sndclose(void);
int sndopen(void);

int wavinfo(byte *in, int len, wavinfo_t *info);
